---
name: "\U0001F41B Bug report"
description: File a bug report
title: "[Bug]: "
labels: ["bug", "status:triage"]
assignees:
  - cytopia

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    attributes:
      label: (Optional) Error message
      description: If you encountered any error message, copy and paste it here. This will be used for googling the issue.
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What went wrong?
      description: What exactly went wrong and what bug did you encounter?
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can we reproduce the bug?
      description: How do you trigger this bug? Please walk us through it step by step in detail. This is crucial in order to triage the bug and support you in resolving it.
    validations:
      required: true

  - type: dropdown
    id: host-os
    attributes:
      label: Host Operating System
      description: What operating system are you using?
      multiple: false
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: dropdown
    id: host-platform
    attributes:
      label: Host Platform (amd64, arm64, other)
      description: What host platform are you running on?
      options:
        - amd64
        - arm64
        - other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: (Linux only) Is SELinux enabled?
      description: When using Linux as your host operating system, check if SELinux is enabled or not.
      options:
        - Yes, SELinux is enabled
        - No, SELinux is disabled
        - I don't know
        - I am not on Linux
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: Docker version
      description: "What Docker version are you using? Please copy and paste the output of `docker --version` into this text area."
    validations:
      required: true

  - type: textarea
    id: log-docker
    attributes:
      label: "Log: docker logs"
      description: "Please copy and paste the output of `docker logs` into this text area"
      render: shell
    validations:
      required: true

  - type: textarea
    attributes:
      label: (Optional) Additional information
      description: Add any additional information that might help with this bug report.
    validations:
      required: false
